_includes:
  - "params_for_model.yaml"

serialized_input_document_list: "%project_root%/output/bert-annotated-ace-documents/list.txt"
# event_type_list: "%project_root%/repos/gaia-event-extraction/data/ACE_event_types.txt"
event_type_list: "%project_root%/params/conflict_attack.txt"
data_split_strategy: "single_split"
training_ratio: 0.5
# ace_file_list: "%project_root%/params/train_shuffle_6.txt"
serialized_model_base: "%project_root%/models/trigger_predictor_keras"
